name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # Vérifie le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Installe les dépendances
    - name: Install dependencies
      run: npm install

    # Exécute les tests
    - name: Run tests
      run: npm test

  restrict-push-to-main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Verify push permissions
      run: |
        if [ "${{ github.actor }}" != "HappyMisfits" ]; then
          echo "Only user 'SteeveO' is allowed to push to the main branch."
          exit 1
        fi